version: "3"
services:
    pisatel:
        build:
            context: .
            args:
                - deployment="true"
        image: pisatel
        container_name: pisatel
        tty: true
        volumes:
            - conf:/usr/src/app/config
            - db:/usr/src/app/db/data
        environment:
            - RACK_ENV=production
        ports:
            - 8080:8080
volumes:
    conf:
    db: