version: "3"
services:
    pisatel:
        build:
            context: .
            args:
                - deployment="true"
        image: pisatel
        container_name: pisatel
        tty: true
        volumes:
            - app:/usr/src/app
        environment:
            - RACK_ENV=production
        ports:
            - 8080:8080
volumes:
    app: