name: Your blog
description: Give it a description
links:
    -
        text: Home
        href: /
    -
        text: Twitter
        href: //twitter.com/your_account
posts:
    per_page: 5
admin:
    login: login
    password: "password"
endpoints:
    graphql:
        type: private # set to public to allow requests to /graphql
js_injection:
    post: |
        console.log("This code will be executed when someone will visit /post/:id");
        console.log($post);
    index: |
        console.log("This code will be executed when someon will visit /");
        console.log('hello world');