production: &production
    adapter: mysql2 # postgres, sqlite, etc.
    host: 0.0.0.0
    port: 3306
    database: pisatel_production
    username: root
    password: password

development:
    <<: *production # the same settings as in the production
    database: pisatel_development # but use another database
